### ISSUE TITLE
Process EXECUTOR_TYPE tests fail on Windows

### ISSUE THREAD

**Issue by okke-formsma** [dchevell/flask-executor#23]
On windows, a number of tests fail. They are tests using the the 'process' EXECUTOR_TYPE:

tests/test_executor.py::test_submit_app_context[process] FAILED               
tests/test_executor.py::test_submit_g_context_process[process] FAILED    
tests/test_executor.py::test_submit_request_context[process] FAILED       
tests/test_executor.py::test_map_app_context[process] FAILED                
tests/test_executor.py::test_map_g_context_process[process] FAILED        
tests/test_executor.py::test_map_request_context[process] FAILED           

I'm not sure how the ProcessPoolExecutor on Windows differs from the one on Linux.
[Full tests output](https://github.com/dchevell/flask-executor/files/3659518/test_output.txt)

https://github.com/dchevell/flask-executor/issues/14 seems to be related.

Here is a way to also run tests on windows / macos for travis;

```yaml
matrix:
  include:
    - os: osx
      language: sh
      python: "3.7"
      # Perform the manual steps on osx to install python3 and activate venv
      before_install:
        - brew update
        - brew upgrade python3
        - python3 -m pip install virtualenv
        - virtualenv .venv -p python3
        - source .venv/bin/activate
    - os: windows
      language: sh
      python: "3.7"
      before_install:
        - choco install python3
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
    - os: windows
      language: sh
      python: "2.7"
      before_install:
        - choco install python2
        - export PATH="/c/Python27:/c/Python27/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
```
